Repository AlchemistSimulator/Alchemist, pull requests merged in 2024-11, with the labels that each got.

#3892 test(loading): run tests on MongoDB v8
  alchemist-loading/src/test/kotlin/it/unibo/alchemist/test/MongoTestUtility.kt
Labels: auto-update-rebase

#3893 fix(loading): do not fail loading if multiple constructors produce the same parameter
  alchemist-loading/src/main/kotlin/it/unibo/alchemist/boundary/loader/util/JVMConstructor.kt
Labels: auto-update-rebase

#3890 feat(euclidean-geometry)!: expose `EuclideanConfigurableMoveNode` as a base (non-abstract) class
  .gitignore
  .idea/vcs.xml
  alchemist-euclidean-geometry/src/main/kotlin/it/unibo/alchemist/model/actions/AbstractEuclideanConfigurableMoveNode.kt
  alchemist-euclidean-geometry/src/main/kotlin/it/unibo/alchemist/model/actions/EuclideanConfigurableMoveNode.kt
  alchemist-euclidean-geometry/src/main/kotlin/it/unibo/alchemist/model/actions/GenericRandomWalker.kt
  alchemist-implementationbase/src/main/java/it/unibo/alchemist/model/actions/AbstractConfigurableMoveNode.java
  alchemist-implementationbase/src/main/java/it/unibo/alchemist/model/actions/MoveToTarget.java
  alchemist-implementationbase/src/main/java/it/unibo/alchemist/model/movestrategies/routing/StraightLine.kt
  alchemist-implementationbase/src/main/kotlin/it/unibo/alchemist/model/movestrategies/target/GoTo.kt
  alchemist-loading/src/test/kotlin/it/unibo/alchemist/test/TestConstructorOverloading.kt
  alchemist-loading/src/test/resources/regression/2024-depots-ambiguous-constructors.yml
Labels: enhancement, blocked, auto-update-rebase

#3938 ci: disable dry-deploy on Maven Central to reduce the stress on OSSRH
  .github/workflows/build-and-deploy.yml
Labels: auto-update-rebase

#3965 fix: do not kick configuration keys just because their name matches a variable.
  alchemist-loading/src/main/kotlin/it/unibo/alchemist/boundary/loader/SimulationModel.kt
Labels: auto-update-rebase

#3963 test(loading): test loading nested variables
  alchemist-loading/src/test/kotlin/it/unibo/alchemist/test/TestKtVariable.kt
  alchemist-loading/src/test/resources/regression/testLoadFormulaVariables.yml
Labels: auto-update-rebase

#3966 perf(loading): early-intercept `String`s, avoiding the loader to go through them as `Iterable`s
  alchemist-loading/src/main/kotlin/it/unibo/alchemist/boundary/loader/SimulationModel.kt
Labels: auto-update-merge
