Repository AlchemistSimulator/Alchemist, pull requests merged in 2025-05, with the labels that each got.

#4451 docs(site): update fieldVMC experiments and paper DOI
  site/content/showcase/2024-fieldvmc/_index.md
Labels: auto-update-rebase

#4377 feat(loading): add different network extractors
  alchemist-loading/src/main/kotlin/it/unibo/alchemist/boundary/extractors/NetworkCentroid.kt
  alchemist-loading/src/main/kotlin/it/unibo/alchemist/boundary/extractors/NetworkDensity.kt
  alchemist-loading/src/main/kotlin/it/unibo/alchemist/boundary/extractors/NetworkDiameter.kt
  alchemist-loading/src/main/kotlin/it/unibo/alchemist/boundary/extractors/NetworkHopDiameter.kt
  alchemist-loading/src/main/kotlin/it/unibo/alchemist/boundary/extractors/NodeDegree.kt
  alchemist-loading/src/main/kotlin/it/unibo/alchemist/boundary/extractors/SubnetworksDiameter.kt
Labels: auto-update-merge

#4465 chore(deps): update graphql to 9.0.0-alpha.8
  gradle/libs.versions.toml
  javadoc-io.json
Labels: dependencies, auto-update-rebase
